# Generated by Django 3.1.7 on 2021-04-03 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'get_latest_by': '-dt', 'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
